before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}'
  main: cmd/cloudlist/main.go

  flags:
    - -trimpath

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

snapcrafts:
  - id: cloudlist
    replacements:
      darwin: macOS
    name: cloudlist
    publish: false
    summary: Cloudlist is a multi-cloud tool for getting Assets (Hostnames, IP Addresses) from Cloud Providers.
    description: |
      Cloudlist is a multi-cloud tool for getting Assets (Hostnames, IP Addresses) from Cloud Providers. This is intended to be used by the blue team to augment Attack Surface Management efforts by maintaining a centralized list of assets across multiple clouds with very little configuration efforts.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      cloudlist:
        command: cloudlist
        plugs:
          - home
          - network
          - removable-media
          - dot-cloudlist
    plugs:
      dot-cloudlist:
        interface: personal-files
        write:
          - $HOME/.config/cloudlist