name: 🔨 Build Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, windows-latest, macOS-12]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build .
        working-directory: cmd/cloudlist/

      - name: Test
        run: go test .
        working-directory: cmd/cloudlist/

      - name: Race Condition Tests
        run: go build -race .
        working-directory: cmd/cloudlist/